# action.yml
name: 'Run postgres command'
description: 'Run a command against a postgres database'
inputs:
  command:
    description: 'The command'
    required: true
  database-url:
    description: url to database
    required: true
runs:
  using: 'docker'
  image: 'postgres:12-alpine'
  args:
    - psql
    - ${{ inputs.database-url }}
    - -c
    - ${{ inputs.command }}
